# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               OpenSage
tagline:             'An engine rewrite'
description:         'A rewrite for the Strategy Aciton Game Engine (=SAGE) from EA.'
url:                 http://feliwir.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Stephan Vedder
  url:               https://twitter.com/StephanVedder
  email:             stephan.vedder@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/feliwir/feliwir.github.io