# Permalinks
permalink:           pretty

# Setup
title:               OpenSage
tagline:             An engine rewrite
url:                 http://feliwir.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Stephan Vedder
  url:               https://twitter.com/mdo
  email:             stephan.vedder@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/feliwir/feliwir.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
